///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CS_View_1_3
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Browser_Logout recording.
    /// </summary>
    [TestModule("f0af03c7-ad51-441c-9afe-02d5a4d35a55", ModuleType.Recording, 1)]
    public partial class Browser_Logout : ITestModule
    {
        /// <summary>
        /// Holds an instance of the CS_View_1_3Repository repository.
        /// </summary>
        public static CS_View_1_3Repository repo = CS_View_1_3Repository.Instance;

        static Browser_Logout instance = new Browser_Logout();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Browser_Logout()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Browser_Logout Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VIEWForClusterStor1.Automation' at 107;9.", repo.VIEWForClusterStor1.AutomationInfo, new RecordItemIndex(0));
            repo.VIEWForClusterStor1.Automation.Click("107;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VIEWForClusterStor1.Logout' at 33;16.", repo.VIEWForClusterStor1.LogoutInfo, new RecordItemIndex(1));
            repo.VIEWForClusterStor1.Logout.Click("33;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'VIEWForClusterStor.LoginShow.Logo'.", repo.VIEWForClusterStor.LoginShow.LogoInfo, new RecordItemIndex(2));
            Validate.Exists(repo.VIEWForClusterStor.LoginShow.LogoInfo);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
